# Generated by Django 2.0.2 on 2018-02-26 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0004_auto_20180207_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='kind',
            field=models.IntegerField(choices=[(0, '搜索代理'), (1, '下载代理')], default=1, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='password',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='retry',
            field=models.IntegerField(default=0, verbose_name='尝试次数'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='speed',
            field=models.IntegerField(default=0, verbose_name='连接速度(ms)'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='status',
            field=models.IntegerField(choices=[(0, '未检测'), (1, '检测成功'), (2, '检测失败')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='user',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='topic',
            name='abstract',
            field=models.TextField(default='', verbose_name='内容简介'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='author',
            field=models.CharField(default='', max_length=200, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='available',
            field=models.CharField(db_index=True, default='', max_length=100, verbose_name='是否可用'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='avatar',
            field=models.CharField(default='', max_length=500, verbose_name='缩略图地址'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(default='', verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='like_num',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='origin_title',
            field=models.CharField(default='', max_length=200, verbose_name='原文标题'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='publish_time',
            field=models.DateTimeField(db_index=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='read_num',
            field=models.IntegerField(default=0, verbose_name='阅读数'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='source',
            field=models.TextField(default='', verbose_name='文章原内容'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='unique_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='url的md5值'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='url',
            field=models.CharField(default='', max_length=500, verbose_name='文章的url'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='wechat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.Wechat', verbose_name='公众号'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='words',
            field=models.IntegerField(default=0, verbose_name='字数'),
        ),
        migrations.AlterField(
            model_name='wechat',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='公众号头像'),
        ),
        migrations.AlterField(
            model_name='wechat',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='wechat',
            name='frequency',
            field=models.IntegerField(default=0, verbose_name='爬取频率, 单位:分钟'),
        ),
        migrations.AlterField(
            model_name='wechat',
            name='intro',
            field=models.TextField(blank=True, default='', verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='wechat',
            name='name',
            field=models.CharField(max_length=100, verbose_name='公众号'),
        ),
        migrations.AlterField(
            model_name='wechat',
            name='next_crawl_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='下次爬取时间'),
        ),
        migrations.AlterField(
            model_name='wechat',
            name='qrcode',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='二维码'),
        ),
        migrations.AlterField(
            model_name='wechat',
            name='status',
            field=models.IntegerField(choices=[(0, '默认'), (1, '禁用'), (2, '删除')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='wechat',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='wechat',
            name='wechatid',
            field=models.CharField(max_length=100, unique=True, verbose_name='公众号id'),
        ),
        migrations.AlterField(
            model_name='word',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='word',
            name='frequency',
            field=models.IntegerField(default=100, verbose_name='爬取频率, 单位:分钟'),
        ),
        migrations.AlterField(
            model_name='word',
            name='intro',
            field=models.TextField(blank=True, default='', verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='word',
            name='kind',
            field=models.IntegerField(choices=[(0, '关键词')], default=0, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='word',
            name='next_crawl_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='下次爬取时间'),
        ),
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.CharField(max_length=100, verbose_name='词'),
        ),
    ]
